env_type: isaaclab
total_num_envs: null
auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1

reward_coef: 1.0
use_fixed_reset_state_ids: False
max_steps_per_rollout_epoch: 256
max_episode_steps: 256 # max episode steps for truncation


video_cfg:
  save_video: False
  info_on_video: True
  fps: 20
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "Isaac-Stack-Cube-Franka-IK-Rel-Visuomotor-Rewarded-v0"
  num_envs: null
  max_episode_steps: ${env.train.max_episode_steps} # max episode steps for truncation
  task_description: "Stack the red block on the blue block, then stack the green block on the red block."
  table_cam:
    height: 256
    width: 256
  wrist_cam:
    height: 256
    width: 256