name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests-cuda:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          UV_TORCH_BACKEND=auto uv sync
          uv pip install transformers

      - name: Run pytest
        timeout-minutes: 20
        run: |
          export PYTHONPATH=$(pwd):$(pwd)/tests/unit_tests
          source .venv/bin/activate
          pytest tests/unit_tests

      - name: Run doctest
        timeout-minutes: 20
        run: |
          source .venv/bin/activate
          pytest --doctest-modules rlinf/scheduler

      - name: Clean up
        run: |
          rm -rf .venv
          uv cache prune

  unit-tests-cpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create environment and install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          UV_TORCH_BACKEND=auto uv sync
          uv pip install pytest
          uv pip install transformers

      - name: Run pytest
        timeout-minutes: 20
        run: |
          export PYTHONPATH=$(pwd):$(pwd)/tests/unit_tests 
          source .venv/bin/activate
          pytest tests/unit_tests
